# Pole star docker-compose.yml
version: "3.7"

services:

  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "pole_star"
      POSTGRES_USER: "pole"
      POSTGRES_PASSWORD: "star"
    ports:
      - 5432:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE: "default"
    volumes:
      - "./data/:/app/data/"
    restart: always

  nginx:
    image: nginx:alpine
    ports:
     - "8000:80"
    volumes:
      - "./conf/pole_star.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend
    restart: always

volumes:
  postgres:
    driver: local
