# Generated by Django 2.2.6 on 2019-10-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.IntegerField()),
                ('name', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=19)),
                ('timestamp', models.DateTimeField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ship')),
            ],
        ),
    ]
